FILE_UPLOAD_ERROR_MESSAGE = "Invalid file type. Please upload a CSV file."
PAG_BANK_PROVIDER_NAME = "PagBank"
PAYPAL_PROVIDER_NAME = "PayPal"
STRIPE_PROVIDER_NAME = "Stripe"
PAYMENT_PROVIDERS = [PAG_BANK_PROVIDER_NAME, PAYPAL_PROVIDER_NAME, STRIPE_PROVIDER_NAME]

FAKE_SMTP_PORT = 587
FAKE_SMTP_SERVER = "smtp.gmail.com"
FAKE_SMTP_USERNAME = "random@gmail.com"
FAKE_SMTP_PASS = "1212zxzx"

PAYMENT_CONFIRMATION_SUBJECT = "Pagamento confirmado!"
